language: cpp

compiler:
 - gcc
 
addons:
 apt:
  packages:
   - cmake
   - cmake-data

before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -H. -B_build -DBUILD_TESTS=ON
  - cmake --build _build
  - cd _build
  - ./check --enable-gcov
after_success:
  - cd ..
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
